//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using Domain.Entities;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class EventManagementEntities : DbContext
    {
        public EventManagementEntities()
            : base("name=EventManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Guest> Guest { get; set; }
        public virtual DbSet<Service> Service { get; set; }
    }
}
